### ISSUE TITLE
Newest GravityForms,  1.8.12  braeks name-field

### ISSUE THREAD

**Issue by Demitjev** [neojp/gravity-forms-placeholders#16]
Hi,

It seems like the newest GF 1.8.12 somehow breaks the name-field in GF. The description of the field shows outside the form field, all other fields works as well. Does anyone have a idea of how to fix this small bug?

Thanks for a great plugin! :)

**Comment by robneu** [comment]
+1 for broken field in the latest version.

**Comment by Demitjev** [comment]
Subject seems to be fixed via latest GF Update;  1.8.13.
