### ISSUE TITLE
Any way to style the placeholder text color etc?

### ISSUE THREAD

**Issue by thecolab** [neojp/gravity-forms-placeholders#9]
This is a really helpful little plugin, much appreciated. I've been trying to style the placeholder text slightly differently and can't seem to get any styles to stick. Possible? I went through the plugin files and can't seem to find the source of it's current color.

**Comment by neojp** [comment]
The styles for `placeholder` attributes can be altered by using CSS.

http://css-tricks.com/snippets/css/style-placeholder-text/

**Comment by rubiwane** [comment]
It's simple:
To change the color of the font in placeholders gravity form, you have to use CSS like this:
How does it works? Gravity Form documentation target the ofrm ID by the part after the first field : 
#form_wrapper_8 -->> 8 is the number of your form.
If your form is 2 write : #gform_wrapper_2

Now the CSS:
#gform_wrapper_8 .gform_fields .gfield input::-webkit-input-placeholder {color: pink;}
